use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use std::{collections::BTreeMap, fs, hash::{Hash, Hasher}, path::{Path, PathBuf}, process::Command, time::{SystemTime, UNIX_EPOCH}};
#[cfg(windows)] use std::os::windows::process::CommandExt;

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
pub struct ChangedFile { pub path: String, pub status: String, pub staged: bool, pub fingerprint: Option<String>, pub preview: Option<String> }
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
pub struct GitSnapshot { pub id: String, pub repo: PathBuf, pub head: Option<String>, pub branch: Option<String>, pub captured_at: u64, pub files: Vec<ChangedFile>, pub staged_diff: String, pub unstaged_diff: String, pub fingerprints: BTreeMap<String,String> }

fn git(repo:&Path, args:&[&str])->Result<Vec<u8>> { let mut c=Command::new("git"); c.args(args).current_dir(repo); #[cfg(windows)] { c.creation_flags(0x08000000); } let o=c.output()?; if !o.status.success(){return Err(anyhow!("git {:?}: {}",args,String::from_utf8_lossy(&o.stderr)));} Ok(o.stdout) }
fn hash(data:&[u8])->String { let mut h=std::collections::hash_map::DefaultHasher::new(); data.hash(&mut h); format!("{:016x}",h.finish()) }
fn text_preview(data:&[u8])->Option<String> { if data.contains(&0) { return None } let s=String::from_utf8_lossy(data); Some(if s.len()>4096 { format!("{}\n[truncated]", &s[..s.char_indices().take(4096).last().map(|(i,_)|i).unwrap_or(0)]) } else { s.into_owned() }) }
pub fn capture(repo:&Path)->Result<GitSnapshot> { let root=fs::canonicalize(repo)?; let head=String::from_utf8(git(&root,&["rev-parse","HEAD"]).unwrap_or_default()).ok().map(|s|s.trim().to_string()).filter(|s|!s.is_empty()); let branch=String::from_utf8(git(&root,&["symbolic-ref","--short","-q","HEAD"]).unwrap_or_default()).ok().map(|s|s.trim().to_string()).filter(|s|!s.is_empty()); let raw=git(&root,&["status","--porcelain=v1","-z"])?; let mut files=Vec::new(); for part in raw.split(|b|*b==0).filter(|p|!p.is_empty()){ let s=String::from_utf8_lossy(part); if s.len()<4 {continue} let code=&s[..2]; let path=s[3..].to_string(); let staged=code.as_bytes()[0]!=b' ' && code.as_bytes()[0]!=b'?'; let full=root.join(&path); let bytes=fs::read(&full).ok(); files.push(ChangedFile{path:path.clone(),status:code.trim().to_string(),staged,fingerprint:bytes.as_deref().map(hash),preview:bytes.as_deref().and_then(text_preview)}); }
 let mut fingerprints=BTreeMap::new(); for p in String::from_utf8_lossy(&git(&root,&["ls-files","-co","--exclude-standard","-z"])?).split('\0').filter(|s|!s.is_empty()){ if let Ok(b)=fs::read(root.join(p)){fingerprints.insert(p.to_string(),hash(&b));} } let staged_diff=String::from_utf8_lossy(&git(&root,&["diff","--cached","--no-ext-diff"])?).into_owned(); let unstaged_diff=String::from_utf8_lossy(&git(&root,&["diff","--no-ext-diff"])?).into_owned(); Ok(GitSnapshot{id:format!("s{}",SystemTime::now().duration_since(UNIX_EPOCH)?.as_millis()),repo:root,head,branch,captured_at:SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs(),files,staged_diff,unstaged_diff,fingerprints}) }
pub fn changes_since(before:&GitSnapshot, after:&GitSnapshot)->Vec<String>{ let mut keys=before.fingerprints.keys().chain(after.fingerprints.keys()).cloned().collect::<Vec<_>>(); keys.sort(); keys.dedup(); keys.into_iter().filter(|k|before.fingerprints.get(k)!=after.fingerprints.get(k)).collect() }
pub fn commits_since(repo:&Path, head:Option<&str>)->Result<String>{ let range=head.map(|h|format!("{}..HEAD",h)); let args:Vec<&str>=match range.as_deref(){Some(r)=>vec!["log","--oneline",r],None=>vec!["log","--oneline"]}; Ok(String::from_utf8_lossy(&git(repo,&args)?).into_owned()) }
pub fn save_snapshot(room:&Path,s:&GitSnapshot)->Result<PathBuf>{let d=room.join("snapshots");fs::create_dir_all(&d)?;let p=d.join(format!("{}.json",s.id));fs::write(&p,serde_json::to_vec_pretty(s)?)?;Ok(p)}
pub fn load_snapshot(room:&Path,id:&str)->Result<GitSnapshot>{Ok(serde_json::from_slice(&fs::read(room.join("snapshots").join(format!("{}.json",id)))?)?)}
